const char* basic_HTML=
"<html>\n"
"<head>\n"
"<title>\n"
"Car Internals - Basic View\n"
"</title>\n"
"</head>\n"
"<body>\n"
"\n"
"<script>\n"
"async function poll() {\n"
"    try {\n"
"        const response = await fetch(\"/data\");\n"
"        \n"
"        if (response.ok) {\n"
"            const data = await response.json();\n"
"            console.log(\"Data received:\", data);\n"
"        } else {\n"
"            console.error(\"Server error:\", response.status);\n"
"        }\n"
"    } catch (error) {\n"
"        console.error(\"Network error:\", error);\n"
"    } finally {\n"
"        // Schedule the next poll only AFTER this one is done\n"
"        setTimeout(poll, 500);\n"
"    }\n"
"}\n"
"\n"
"// Start the first poll\n"
"poll();\n"
"</script>\n"
"</body>\n"
"</html>";