const char* config_html =
"<!DOCTYPE html><html lang='en'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>BERT.26 Config</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:monospace;background:#111;color:#eee;padding:8px;font-size:13px}"
"h2{font-size:18px;letter-spacing:2px}"
".hdr{display:flex;align-items:center;justify-content:space-between;background:#1a1a1a;border-radius:6px;padding:10px 14px;margin-bottom:8px;border:1px solid #333}"
".sect{background:#1a1a1a;border:1px solid #333;border-radius:6px;padding:14px;margin-bottom:8px}"
".sect h3{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:12px}"
".frow{display:flex;align-items:center;gap:8px;margin-bottom:10px;flex-wrap:wrap}"
"label{color:#aaa;font-size:12px;min-width:110px}"
"input[type=number]{background:#222;border:1px solid #444;color:#eee;padding:6px 8px;border-radius:4px;"
"font-family:monospace;font-size:14px;width:110px}"
"input[type=number]:focus{outline:none;border-color:#4af}"
"button{background:#1a2a3a;border:1px solid #4af;color:#4af;padding:6px 14px;border-radius:4px;"
"font-family:monospace;font-size:12px;cursor:pointer}"
"button:hover{background:#4af;color:#000}"
".st{font-size:12px;padding:4px 0;min-height:20px;margin-top:4px}"
".ok{color:#4f4}.err{color:#f44}"
".info{color:#666;font-size:11px;line-height:1.6;margin-bottom:12px;border-left:2px solid #2a2a2a;padding-left:8px}"
"a.back{color:#4af;text-decoration:none;font-size:12px;padding:3px 9px;border:1px solid #4af;border-radius:4px}"
"</style></head><body>"

"<div class='hdr'>"
"<h2>BERT.26 Config</h2>"
"<a href='/' class='back'>&#8592; Back</a>"
"</div>"

"<div class='sect'>"
"<h3>State of Charge Override</h3>"
"<p class='info'>Current SOC from BMS: <span id='cur_soc'>--</span>%<br>"
"Sends CAN 0x314. BMS replaces its SOC estimate immediately.</p>"
"<div class='frow'>"
"<label>SOC (%)</label>"
"<input type='number' id='soc_val' min='0' max='100' step='0.1' placeholder='0.0'>"
"<button onclick='setSoc()'>Send</button>"
"</div>"
"<div class='st' id='soc_st'></div>"
"</div>"

"<div class='sect'>"
"<h3>Current Sensor Calibration</h3>"
"<p class='info'>Two-point linear calibration via CAN 0x315.<br>"
"1. Apply a known current, enter the value below, send Point 1.<br>"
"2. Apply a different known current, enter the value, send Point 2.<br>"
"BMS computes gain + offset and saves to EEPROM. Negative = regen/charge.</p>"
"<div class='frow'>"
"<label>Point 1 (A)</label>"
"<input type='number' id='c1' min='-500' max='500' step='0.1' placeholder='0.0'>"
"<button onclick='sendCal(1)'>Send Pt 1</button>"
"</div>"
"<div class='frow'>"
"<label>Point 2 (A)</label>"
"<input type='number' id='c2' min='-500' max='500' step='0.1' placeholder='0.0'>"
"<button onclick='sendCal(2)'>Send Pt 2</button>"
"</div>"
"<div class='st' id='cal_st'></div>"
"</div>"

"<script>"
"fetch('/data').then(r=>r.json()).then(d=>"
"document.getElementById('cur_soc').textContent=Math.round(d.SOC)"
").catch(()=>{});"

"function setS(id,msg,cls){"
"const e=document.getElementById(id);"
"e.textContent=msg;e.className='st '+(cls||'');}"

"function doPost(url,body,sid){"
"fetch(url,{method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:body})"
".then(r=>r.json())"
".then(d=>setS(sid,d.ok?'Sent OK':'Error: '+(d.error||'?'),d.ok?'ok':'err'))"
".catch(()=>setS(sid,'Request failed','err'));}"

"function setSoc(){"
"const v=parseFloat(document.getElementById('soc_val').value);"
"if(isNaN(v)||v<0||v>100){setS('soc_st','Must be 0-100','err');return;}"
"doPost('/set_soc','soc='+encodeURIComponent(v.toFixed(1)),'soc_st');}"

"function sendCal(pt){"
"const v=parseFloat(document.getElementById(pt===1?'c1':'c2').value);"
"if(isNaN(v)){setS('cal_st','Enter a current value in Amps','err');return;}"
"doPost('/set_cal','point='+pt+'&current='+encodeURIComponent(v.toFixed(1)),'cal_st');}"
"</script></body></html>";
