const char* base_html =
"<!DOCTYPE html><html lang='en'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>BERT.26 BMS</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:monospace;background:#111;color:#eee;padding:8px;font-size:13px}"
"h2{font-size:18px;letter-spacing:2px}"
".hdr{display:flex;align-items:center;justify-content:space-between;background:#1a1a1a;border-radius:6px;padding:10px 14px;margin-bottom:8px;border:1px solid #333}"
".dot{width:11px;height:11px;border-radius:50%;display:inline-block;margin-right:5px;vertical-align:middle}"
".live{background:#0f0;box-shadow:0 0 7px #0f0}.stale{background:#fa0;box-shadow:0 0 7px #fa0}.offline{background:#f44;box-shadow:0 0 7px #f44}"
".g2{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px}"
".g3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:8px}"
".card{background:#1a1a1a;border:1px solid #333;border-radius:6px;padding:10px}"
".card h3{font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:8px}"
".big{font-size:30px;font-weight:bold;line-height:1}"
".row{display:flex;justify-content:space-between;align-items:center;padding:2px 0;border-bottom:1px solid #222}"
".lbl{color:#888;font-size:11px}.val{font-weight:bold}"
".ok{color:#4f4}.warn{color:#fa0}.fault{color:#f44;font-weight:bold}.dim{color:#666}"
".soc-bar{height:18px;background:#2a2a2a;border-radius:3px;overflow:hidden;margin:6px 0}"
".soc-fill{height:100%;transition:width 0.4s,background 0.4s}"
".sect{background:#1a1a1a;border:1px solid #333;border-radius:6px;padding:10px;margin-bottom:8px}"
".sect h3{font-size:10px;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:8px}"
".cgrid{display:grid;grid-template-columns:repeat(12,1fr);gap:2px;margin-top:4px}"
".cell{height:28px;border-radius:2px;font-size:8px;display:flex;align-items:center;justify-content:center;"
"cursor:default;font-weight:bold;color:#111;text-shadow:0 0 4px rgba(255,255,255,0.65);transition:background 0.5s;overflow:hidden}"
".legend{margin-top:6px;font-size:10px;color:#888;display:flex;gap:10px;flex-wrap:wrap;align-items:center}"
".cfgbtn{color:#4af;text-decoration:none;font-size:12px;padding:3px 9px;border:1px solid #4af;border-radius:4px}"
"</style></head><body>"

"<div class='hdr'>"
"<h2>BERT.26 BMS</h2>"
"<div style='display:flex;align-items:center;gap:12px'>"
"<a href='/config' class='cfgbtn'>Config</a>"
"<div>"
"<span class='dot offline' id='dot'></span><span id='status'>OFFLINE</span>"
"&nbsp;&nbsp;<span id='age' style='color:#666;font-size:11px'></span>"
"</div></div></div>"

"<div class='g3'>"
"<div class='card'><h3>State of Charge</h3>"
"<div class='big' id='soc'>--</div>"
"<div class='soc-bar'><div class='soc-fill' id='socfill' style='width:0%'></div></div>"
"</div>"
"<div class='card'><h3>Pack Current</h3>"
"<div class='big' id='cur'>--</div>"
"<div class='lbl' style='margin-top:4px'>A &nbsp;(+ discharge / &#8722; regen)</div>"
"</div>"
"<div class='card'><h3>BMS Status</h3>"
"<div id='flags'>--</div><div id='fcode' style='margin-top:5px;font-size:12px'></div>"
"</div></div>"

"<div class='g2'>"
"<div class='card'><h3>Cell Voltages</h3>"
"<div class='row'><span class='lbl'>Min</span><span class='val' id='vmin'>--</span></div>"
"<div class='row'><span class='lbl'>Max</span><span class='val' id='vmax'>--</span></div>"
"<div class='row'><span class='lbl'>Avg</span><span class='val' id='vavg'>--</span></div>"
"<div class='row'><span class='lbl'>Spread</span><span class='val' id='vspread'>--</span></div>"
"</div>"
"<div class='card'><h3>Temperatures</h3>"
"<div class='row'><span class='lbl'>Min</span><span class='val' id='tmin'>--</span></div>"
"<div class='row'><span class='lbl'>Max</span><span class='val' id='tmax'>--</span></div>"
"<div class='row'><span class='lbl'>Avg</span><span class='val' id='tavg'>--</span></div>"
"</div></div>"

"<div class='sect'>"
"<h3>Cell Voltages &mdash; 96 cells &nbsp;<span id='vcage' style='color:#444;font-size:10px'>waiting&hellip;</span></h3>"
"<div class='cgrid' id='vcells'></div>"
"<div class='legend'>"
"<span style='color:#e03333'>&#9679; &lt;2.5 V fault</span>"
"<span style='color:rgb(210,130,0)'>&#9679; 2.5&ndash;3.2 V low</span>"
"<span style='color:rgb(40,200,40)'>&#9679; 3.5 V nominal</span>"
"<span style='color:rgb(0,170,210)'>&#9679; 3.8&ndash;4.0 V</span>"
"<span style='color:#e03333'>&#9679; &gt;4.2 V fault</span>"
"<span style='color:#444'>&#9679; invalid</span>"
"</div></div>"

"<div class='sect'>"
"<h3>Cell Temperatures &mdash; 96 cells &nbsp;<span id='tcage' style='color:#444;font-size:10px'>waiting&hellip;</span></h3>"
"<div class='cgrid' id='tcells'></div>"
"<div class='legend'>"
"<span style='color:rgb(0,100,220)'>&#9679; cold</span>"
"<span style='color:rgb(40,200,40)'>&#9679; 20&ndash;35 &#176;C nominal</span>"
"<span style='color:rgb(220,180,0)'>&#9679; 45 &#176;C warm</span>"
"<span style='color:#e03333'>&#9679; &gt;52 &#176;C fault</span>"
"<span style='color:#444'>&#9679; no sensor</span>"
"</div></div>"

"<div class='sect' id='chg' style='display:none'><h3>Charger</h3>"
"<div class='g3'>"
"<div><div class='lbl'>Output Voltage</div><span class='val' id='cv'>--</span> V</div>"
"<div><div class='lbl'>Output Current</div><span class='val' id='cc'>--</span> A</div>"
"<div><div class='lbl'>Status</div><span class='val' id='cf'>--</span></div>"
"</div></div>"

"<script>"
"const FAULT=['None','Cell UV','Cell OV','Pack UV','Pack OV','Over Temp','Spread','Precharge Timeout','Precharge Fast','IMD','Charger Comms','BQ Init','BQ Comms'];"
"let lastOk=0,vcHasData=false,tcHasData=false;"

"function lerp(a,b,t){return Math.round(a+(b-a)*t)}"
"function gclr(stops,v){"
"for(let i=0;i<stops.length-1;i++){"
"if(v>=stops[i][0]&&v<=stops[i+1][0]){"
"const t=(v-stops[i][0])/(stops[i+1][0]-stops[i][0]);"
"const a=stops[i][1],b=stops[i+1][1];"
"return'rgb('+lerp(a[0],b[0],t)+','+lerp(a[1],b[1],t)+','+lerp(a[2],b[2],t)+')';}"
"}return'#333';}"

"const VS=[[2.5,[220,100,0]],[3.2,[180,210,0]],[3.7,[40,200,40]],[4.0,[0,170,210]],[4.2,[200,80,0]]];"
"const TS=[[-10,[0,80,200]],[20,[0,180,160]],[35,[40,200,40]],[45,[220,180,0]],[52,[220,60,0]]];"

"function vColor(mv){"
"if(mv===65535||mv===0)return'#2a2a2a';"
"const v=mv/1000;"
"return(v<2.5||v>4.2)?'#e03333':gclr(VS,v);}"

"function tColor(t){"
"if(t===null)return'#2a2a2a';"
"return t>52?'#e03333':gclr(TS,Math.max(-10,t));}"

"function buildGrid(id,arr,colorFn,ttFn,dispFn){"
"const el=document.getElementById(id);"
"if(el.children.length!==arr.length){"
"el.innerHTML='';"
"for(let i=0;i<arr.length;i++){"
"const d=document.createElement('div');"
"d.className='cell';d.id=id+'_'+i;el.appendChild(d);}}"
"for(let i=0;i<arr.length;i++){"
"const d=document.getElementById(id+'_'+i);"
"d.style.background=colorFn(arr[i]);"
"d.title='Cell '+(i+1)+': '+ttFn(arr[i]);"
"d.textContent=dispFn(arr[i]);}}"

"function tv(v,unit){return v<-0.5?'N/A':v.toFixed(unit==='V'?3:0)+' '+unit;}"

"function fetch_data(){"
"fetch('/data').then(r=>r.json()).then(d=>{"
"const now=Date.now();lastOk=now;"
"const soc=Math.round(d.SOC);"
"document.getElementById('soc').textContent=soc+'%';"
"const sf=document.getElementById('socfill');"
"sf.style.width=soc+'%';"
"sf.style.background=soc>20?'linear-gradient(90deg,#0a0,#4f4)':'linear-gradient(90deg,#900,#f44)';"
"const c=d.PackCurrent,cel=document.getElementById('cur');"
"cel.textContent=(c>=0?'+':'')+c.toFixed(1);"
"cel.className='big '+(c<0?'ok':'');"
"document.getElementById('vmin').textContent=tv(d.CellVMin,'V');"
"document.getElementById('vmax').textContent=tv(d.CellVMax,'V');"
"document.getElementById('vavg').textContent=tv(d.CellVAvg,'V');"
"const sp=Math.round((d.CellVMax-d.CellVMin)*1000);"
"const se=document.getElementById('vspread');"
"se.textContent=sp+' mV';"
"se.className='val '+(sp>200?'fault':sp>100?'warn':'ok');"
"document.getElementById('tmin').textContent=tv(d.TempMin,'\\u00b0C');"
"document.getElementById('tmax').textContent=tv(d.TempMax,'\\u00b0C');"
"document.getElementById('tavg').textContent=tv(d.TempAvg,'\\u00b0C');"
"const flags=Math.round(d.BmsFlags);"
"const fault=flags&1,cont=(flags>>1)&1,chrg=(flags>>2)&1;"
"document.getElementById('flags').innerHTML="
"'<div class=\"'+(fault?'fault':'ok')+'\">'+(fault?'&#9888; FAULT ACTIVE':'&#10003; No Fault')+'</div>'"
"+'<div class=\"'+(cont?'ok':'warn')+'\">'+(cont?'&#10003; Contactors Closed':'&#9679; Contactors Open')+'</div>'"
"+'<div class=\"'+(chrg?'ok':'dim')+'\">'+(chrg?'&#10003; Charge Mode':'&#9679; Drive Mode')+'</div>';"
"const fc=Math.round(d.FaultCode),fe=document.getElementById('fcode');"
"fe.textContent=fc?'Fault: '+(FAULT[fc]||('Code '+fc)):'';"
"fe.className=fc?'fault':'';"
"if(d.cellVoltages&&d.cellVoltages.length){"
"buildGrid('vcells',d.cellVoltages,vColor,"
"mv=>mv===65535?'invalid':(mv/1000).toFixed(3)+' V',"
"mv=>mv===65535||mv===0?'--':(mv/1000).toFixed(2));"
"vcHasData=true;}"
"if(vcHasData)document.getElementById('vcage').textContent='refreshes every 10s';"
"if(d.cellTemps&&d.cellTemps.length){"
"buildGrid('tcells',d.cellTemps,tColor,"
"t=>t===null?'no sensor':t+'\\u00b0C',"
"t=>t===null?'--':t+'\\u00b0');"
"tcHasData=true;}"
"if(tcHasData)document.getElementById('tcage').textContent='refreshes every 10s';"
"const showChg=chrg||d.ChargerVoltage>1;"
"document.getElementById('chg').style.display=showChg?'':'none';"
"if(showChg){"
"document.getElementById('cv').textContent=d.ChargerVoltage.toFixed(1);"
"document.getElementById('cc').textContent=d.ChargerCurrent.toFixed(1);"
"const cf=Math.round(d.ChargerFlags),fls=[];"
"if(cf&1)fls.push('HW Fault');"
"if(cf&2)fls.push('Temp');"
"if(cf&4)fls.push('AC Fault');"
"if(cf&8)fls.push('No AC');"
"if(cf&16)fls.push('Timeout');"
"const cfe=document.getElementById('cf');"
"cfe.textContent=fls.length?fls.join(', '):'OK';"
"cfe.className='val '+(fls.length?'fault':'ok');}"
"}).catch(()=>{});}"

"setInterval(()=>{"
"if(!lastOk)return;"
"const age=(Date.now()-lastOk)/1000;"
"document.getElementById('age').textContent=age.toFixed(1)+'s ago';"
"const dot=document.getElementById('dot'),st=document.getElementById('status');"
"if(age<3){dot.className='dot live';st.textContent='LIVE';}"
"else if(age<10){dot.className='dot stale';st.textContent='STALE';}"
"else{dot.className='dot offline';st.textContent='OFFLINE';}"
"},500);"

"fetch_data();"
"setInterval(fetch_data,1000);"
"</script></body></html>";
